services:
  mysqldb:
    image: mysql:8.0
    container_name: catalog_service_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: catalog_service_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "5439:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - services_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  catalog-service-app:
    build:
      context: .
    hostname: catalog-service_app
    container_name: catalog-service_app
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8088:8088"
    env_file:
      - .env
    environment:
      SERVER_PORT: 8088
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

#      STUDENT_SERVICE_URL:  ${STUDENT_SERVICE_URL}
#      PROFESSOR_SERVICE_URL: ${PROFESSOR_SERVICE_URL}

      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500

    networks:
      - services_net
      - shared_net

networks:
  services_net:
    name: services_net
    driver: bridge
  shared_net:
    external: true

volumes:
  db_data:
